ARG GOLANG_IMAGE_TAG=1.18
FROM golang:${GOLANG_IMAGE_TAG} as build

FROM myoung34/github-runner:latest as runner
ARG TERRAFORM_VERSION=1.1.6
ARG GO_VERSION=1.18
ENV GOPATH=/go
ENV PATH=$PATH:/usr/local/go/bin
ENV EPHEMERAL=true
ENV DISABLE_AUTO_UPDATE=true
COPY --from=build /go/bin /usr/local/go/bin

RUN apt update && apt install -y curl zip coreutils jq && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
    export ARCH=$(uname -m | sed 's/x86_64/amd64/g') && \
    curl '-#' -fL -o /tmp/go.tar.gz https://go.dev/dl/go${GO_VERSION}.linux-$ARCH.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    curl '-#' -fL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_$ARCH.zip && \
	unzip -q -d /bin/ /tmp/terraform.zip && \
	rm -f /tmp/terraform.zip && \
    rm -f /tmp/go.tar.gz

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/ephemeral-runner.sh"]