ARG GOLANG_IMAGE_TAG=1.17
FROM golang:${GOLANG_IMAGE_TAG} as build
ARG TFLINT_VERSION=v0.34.1
COPY GNUmakefile /src/GNUmakefile
COPY scripts /src/scripts
RUN cd /src && \
    apt update && \
    apt install -y zip  && \
    make tools

FROM myoung34/github-runner:latest as runner
ARG TERRAFORM_VERSION=1.1.6
ARG TFLINT_AZURERM_VERSION=0.14.0
ARG GO_VERSION=1.18
ENV TFLINT_PLUGIN_DIR /tflint
ENV GOPATH=/go
ENV PATH=$PATH:/usr/local/go/bin
ENV EPHEMERAL=true
ENV DISABLE_AUTO_UPDATE=true
COPY --from=build /go/bin /usr/local/go/bin
COPY --from=build /usr/local/bin/tflint /bin/tflint

RUN apt update && apt install -y curl zip python3 pip coreutils jq && \
    pip install checkov && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
    export ARCH=$(uname -m | sed 's/x86_64/amd64/g') && \
    curl '-#' -fL -o /tmp/go.tar.gz https://go.dev/dl/go${GO_VERSION}.linux-$ARCH.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    curl '-#' -fL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_$ARCH.zip && \
	unzip -q -d /bin/ /tmp/terraform.zip && \
	curl '-#' -fL -o /tmp/tflint-ruleset-azurerm.zip https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/v${TFLINT_AZURERM_VERSION}/tflint-ruleset-azurerm_linux_$ARCH.zip && \
	mkdir -p $TFLINT_PLUGIN_DIR/github.com/terraform-linters/tflint-ruleset-azurerm/$TFLINT_AZURERM_VERSION && \
    unzip -q -d $TFLINT_PLUGIN_DIR/github.com/terraform-linters/tflint-ruleset-azurerm/$TFLINT_AZURERM_VERSION /tmp/tflint-ruleset-azurerm.zip && \
	rm -f /tmp/terraform.zip && \
    rm -f /tmp/tflint-ruleset-azurerm.zip && \
    rm -f /tmp/go.tar.gz

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/ephemeral-runner.sh"]